/* ============================================================
   data.js — the app's data layer
   ------------------------------------------------------------
   Everything in this file is "the database" for the demo.
   You will replace these with real data sources later (a
   Google Sheet, Firestore, Airtable, etc.). Until then, this
   file is the single source of truth — edit it to add tasks,
   members, or settings.
   ============================================================ */

// 15 sample tasks. Mirrors the columns in the Excel template.
window.FF_TASKS = [
  { id: "T01", name: "Attend the First-Timer's Welcome",
    category: "Conference Anchor", proof: "Signature", points: 3,
    where: "Main Hall · Day 1, 9:00 AM",
    mission: "Article XI – Creed: shared experience and fellowship.",
    description: "Open the welcome session for first-timers and get a signature from the host.",
    icon: "✍️" },
  { id: "T02", name: "Meet a National Board Member",
    category: "Networking", proof: "Signature", points: 3,
    where: "Networking Lounge · Days 1-3",
    mission: "Strategic Goal 1: Increase value of ESP National to chapters.",
    description: "Find a National Board member, introduce yourself, ask one question about ESP's direction, and get their signature.",
    icon: "✍️" },
  { id: "T03", name: "Visit the Poster Session",
    category: "Professional Development", proof: "Photo", points: 2,
    where: "Hall B · Day 2, 11:00 AM-1:00 PM",
    mission: "Strategic Goal 2: Foster excellence in the Extension professional.",
    description: "Walk the poster session and snap a photo with one poster whose work surprised you.",
    icon: "📷" },
  { id: "T04", name: "Selfie at the Centennial Countdown Wall",
    category: "ESP Identity", proof: "Photo", points: 2,
    where: "Lobby · Anytime",
    mission: "ESP heritage and the path to 100 years.",
    description: "Find the Centennial countdown wall in the lobby and take a selfie. Bonus points if you tag your home chapter.",
    icon: "📷" },
  { id: "T05", name: "Knowledge Check: Opening Keynote",
    category: "Knowledge", proof: "Quiz", points: 2,
    where: "After Day 1 keynote",
    mission: "Strategic Goal 2: Excellence through professional development.",
    description: "Confirm you absorbed the keynote with one quick check.",
    icon: "❓",
    quiz: { q: "What was the one-word theme the keynote speaker repeated three times?",
            a: ["connection"] } },
  { id: "T06", name: "Introduce Yourself to Three New Chapters",
    category: "Networking", proof: "Signature", points: 4,
    where: "Anywhere · By end of Day 2",
    mission: "Strategic Goal 1: Connect chapters across the country.",
    description: "Get a signature from one member each from three chapters that aren't your own.",
    icon: "✍️" },
  { id: "T07", name: "Attend a Committee Meeting",
    category: "Professional Development", proof: "Signature", points: 3,
    where: "See conference program · Day 2",
    mission: "Article I – Mission: governance through committees.",
    description: "Sit in on any National committee meeting and get the chair's signature.",
    icon: "✍️" },
  { id: "T08", name: "Knowledge Check: A Scholarship I Could Apply For",
    category: "Knowledge", proof: "Quiz", points: 3,
    where: "After visiting the Awards & Scholarships booth",
    mission: "Strategic Goal 2: Professional development opportunities.",
    description: "Find one scholarship at the Awards booth that you'd actually be eligible for.",
    icon: "❓",
    quiz: { q: "Name one scholarship presented at the Awards booth.",
            a: ["chapter at risk", "international fellowship", "professional development grant",
                "siil", "global relations"] } },
  { id: "T09", name: "Photo with a Mentor",
    category: "Networking", proof: "Photo", points: 3,
    where: "Anywhere · Days 1-3",
    mission: "Article XI – Creed: 'share with others the lessons of my experience.'",
    description: "Identify someone whose career you'd like to learn from, ask them to be a mentor for the next year, and take a photo together.",
    icon: "📷" },
  { id: "T10", name: "Visit Your Regional Caucus",
    category: "ESP Identity", proof: "Signature", points: 2,
    where: "See conference program · Day 2",
    mission: "Strategic Goal: Enhance chapter leader engagement at National level.",
    description: "Sit in on your region's caucus and get the regional director's signature.",
    icon: "✍️" },
  { id: "T11", name: "Knowledge Check: First-Timer's Session",
    category: "Knowledge", proof: "Quiz", points: 2,
    where: "After the First-Timer's session, Day 1",
    mission: "Article XI – Creed: fellowship and shared learning.",
    description: "Quick check on what was covered in the first-timer session.",
    icon: "❓",
    quiz: { q: "What is the name of the program that pairs first-timers with experienced members?",
            a: ["mentor", "mentorship", "first five mentor"] } },
  { id: "T12", name: "Sign Up for a Committee for Next Year",
    category: "Engagement", proof: "Signature", points: 4,
    where: "Membership table · Days 2-3",
    mission: "Strategic Goal 1: Connect national committees to chapter units.",
    description: "Pick a National committee that interests you and sign up. Get a signature from the membership table.",
    icon: "✍️" },
  { id: "T13", name: "Attend a Session Outside Your Discipline",
    category: "Professional Development", proof: "Photo", points: 2,
    where: "Any breakout · Days 1-3",
    mission: "Strategic Goal 2: Multi-disciplinary professional development.",
    description: "Pick a breakout outside your usual area and snap a photo of one slide that taught you something new.",
    icon: "📷" },
  { id: "T14", name: "Closing Banquet Attendance",
    category: "Conference Anchor", proof: "Signature", points: 3,
    where: "Banquet Hall · Final evening",
    mission: "ESP heritage and recognition tradition.",
    description: "Attend the closing banquet and get the host chapter representative's signature on the way out.",
    icon: "✍️" },
  { id: "T15", name: "Reflection: What Will You Bring Home?",
    category: "Engagement", proof: "Quiz", points: 2,
    where: "Last day, after closing remarks",
    mission: "Article XI – Creed: 'apply lessons learned' to my home work.",
    description: "Tell us in one or two words what you'll do at home first.",
    icon: "❓",
    quiz: { q: "In one or two words, what's the first thing you'll do at home?",
            a: [] /* empty array = accept any non-blank answer */ } },
];

// Sample roster. In production, load from your member portal CSV.
window.FF_MEMBERS = [
  { email: "tyrone@example.org", name: "Tyrone Gentry",   chapter: "Texas Alpha",   year: 2,
    headline: "I'd love to talk to someone about: 4-H program design." },
  { email: "marisol@example.org", name: "Marisol Vega",    chapter: "California Beta", year: 1,
    headline: "I'd love to talk to someone about: rural broadband adoption." },
  { email: "denzel@example.org", name: "Denzel Carter",    chapter: "Georgia Gamma",  year: 3,
    headline: "I'd love to talk to someone about: livestock economics." },
  { email: "fiona@example.org",  name: "Fiona O'Connell",  chapter: "Iowa Delta",     year: 2,
    headline: "I'd love to talk to someone about: nutrition curriculum for K-5." },
  { email: "jamal@example.org",  name: "Jamal Whitfield",  chapter: "Florida Epsilon", year: 4,
    headline: "I'd love to talk to someone about: state-fair extension exhibits." },
  { email: "anya@example.org",   name: "Anya Okonkwo",     chapter: "New York Zeta",  year: 1,
    headline: "I'd love to talk to someone about: climate-smart small farms." },
];

// Settings (mirrors the Settings tab in the Excel template)
window.FF_SETTINGS = {
  conferenceName: "ESP National Conference 2026",
  conferenceStart: "2026-10-05",
  conferenceEnd: "2026-10-08",
  targetPoints: 20,
  bronze: 8,
  silver: 14,
  gold: 20,
  chatEnabled: true,
  moderationEmail: "membership@espnational.org",
};

// Sample chat thread (only used for demonstration).
window.FF_DEMO_CHAT = {
  "marisol@example.org": [
    { from: "marisol@example.org", text: "Hi Tyrone! Saw you're from Texas — your poster on 4-H curriculum was excellent.", t: Date.now() - 1000 * 60 * 60 * 3 },
    { from: "self", text: "Thanks Marisol! Are you going to the closing banquet tonight?", t: Date.now() - 1000 * 60 * 90 },
    { from: "marisol@example.org", text: "Yes — let's grab a table together.", t: Date.now() - 1000 * 60 * 60 },
  ]
};
